### ISSUE TITLE
Missing exports in index.js

### ISSUE THREAD

**Issue by vrblymt** [kyndryl-design-system/shidoka-applications#247]
There is no exported member of the module progressBar and codeView(blockCodeView and inlineCodeView).

![image](https://github.com/user-attachments/assets/796d96a4-7ead-4cc3-8ffd-25a09e68f55a)
![image](https://github.com/user-attachments/assets/42fe4d60-1a90-4a80-a63b-0b7bc778baa1)

I could only import it directly from the component folder.
![image](https://github.com/user-attachments/assets/71132e11-f6ae-473c-a878-b57a836fbb1b)

Version:
"@kyndryl-design-system/shidoka-applications": "^1.39.1"

**Comment by brian-patrick-3** [comment]
@vrblymt You should always import component files directly, because it doesn't tree shake properly due to side effects.

@wbarbee I think we need to make a couple of changes here:
1. The Code View folder structure kinda breaks our standard import structure, and makes the import path on the Docs pages incorrect. We should probably bring the `blockCodeView` and `inlineCodeView` folders up a level, so the import paths are consistent with our other components.
2. Add the Progress Bar and Code View component exports to `src/index.ts`. In 2.0 I may consider removing this file, since it's recommend to import files directly anyway.

**Comment by brian-patrick-3** [comment]
Resolved by #248

**Comment by brian-patrick-3** [comment]
Released as v1.39.2
